on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        # node: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        # node: [4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        node: [14]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Setup
        run: |
          wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-4.0.2.tgz
          tar xf mongodb-linux-x86_64-ubuntu1604-4.0.2.tgz
          mkdir -p ./data/db/27017 ./data/db/27000
          printf "\n--timeout 8000" >> ./test/mocha.opts
          ./mongodb-linux-x86_64-ubuntu1604-4.0.2/bin/mongod --fork --dbpath ./data/db/27017 --syslog --port 27017
          sleep 2
          mongod --version
          mkdir ./test/typescript/node_modules
          ln -s `pwd` ./test/typescript/node_modules/mongoose

      - run: PATH=`pwd`/mongodb-linux-x86_64-ubuntu1604-4.0.2/bin/:$PATH npm test

  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - run: npm install

      - name: Linter
        run: npm run lint
